name: 02 - Workflow Events

on:
  push:
    branches: [main]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: "I've been triggered by a(n) ${{github.event_name}} event."