name: 04 - Using Actions

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm ci
        working-directory: 04-using-actions/react-app
      - name: Check File Existence
        run: |
          cd 04-using-actions/react-app
          ls -l 
          cat setupTests.js

      - name: Debug `vite.config.js`
        run: |
          echo "Current directory: $(pwd)"
          echo "Setup files path: $(node -e \"console.log(require('path').resolve('setupTests.js'))\")"

      - name: Run Unit Tests
        run: npm test -- --run --reporter verbose



        
             # Things we want to do
             # 0. Checkout the code from the repository
             # 1. Install the dependencies of our react application
             # 2. Execute automated tests


