name: 04 - Using Actions

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04-using-actions/react-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug - Check current directory and files
        run: |
          echo "Current directory:"
          pwd
          echo "List files:"
          ls -la

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm test




             # Things we want to do
             # 0. Checkout the code from the repository
             # 1. Install the dependencies of our react application
             # 2. Execute automated tests


