name: 11 - Using Multiple jobs for Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: Whether to execute cache step
        type: boolean
        default: true
      node-version:
        description: Node version to use
        type: choice
        options:
          - 18.x
          - 20.x
          - 21.x
          - 22.x
        default: 20.x

jobs:
  install-deps:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 11-caching2/react-app
    outputs:
      deps-cache-key: ${{ steps.cache-key.outputs.CACHE_KEY}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Calculate Cache Key
        id: cache-key
        run: |
          echo "CACHE_KEY=deps-node-modules-${{ runner.os }}-node-${{ inputs.node-version }}-deps-${{ hashFiles('11-caching2/react-app/package-lock.json') }}" >> "$GITHUB_OUTPUT"

      - name: Download Cached Dependencies
        if: ${{ inputs.use-cache }}
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: 11-caching2/react-app/node_modules
          key: ${{ steps.cache-key.outputs.CACHE_KEY }}

      - name: Check Cached Dependencies
        run: ls -la 11-caching2/react-app/node_modules || echo "No node_modules directory found"

      - name: Install Dependencies (if cache missed)
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm ci

  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 11-caching2/react-app
    needs: install-deps
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Download Cached Dependencies
        if: ${{ inputs.use-cache }}
        uses: actions/cache@v3
        with:
          path: 11-caching2/react-app/node_modules
          key: ${{ needs.install-deps.outputs.deps-cache-key }}

      - name: Check Cached Dependencies
        run: ls -la 11-caching2/react-app/node_modules || echo "No node_modules directory found"

      - name: Reinstall Dependencies if Cache is Broken
        run: npm ci

      - name: Debug - List Installed Packages
        run: npm list --depth=0

      - name: Testing
        run: npx vitest

      - name: Linting
        run: echo "Linting..."

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 11-caching2/react-app
    needs: install-deps
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Download Cached Dependencies
        if: ${{ inputs.use-cache }}
        uses: actions/cache@v3
        with:
          path: 11-caching2/react-app/node_modules
          key: ${{ needs.install-deps.outputs.deps-cache-key }}

      - name: Check Cached Dependencies
        run: ls -la 11-caching2/react-app/node_modules || echo "No node_modules directory found"

      - name: Reinstall Dependencies if Cache is Broken
        run: npm ci

      - name: Building
        run: npm run build

      - name: Deploying to nonprod
        run: echo "Deploying to nonprod environment"