name: 11 - Using Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: Whether to execute cache step
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 11-caching/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug - Check current directory and files
        run: |
          echo "Current directory:"
          pwd
          echo "List files:"
          ls -la

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: npm ci
      - name: Testing 
        run: npm test
      - name: Buiding
        run: npm build
      - name: Deploying to nonprod
        run: echo "Deploying to nonprod"


 
