name: 11 - Using Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: Whether to execute cache step
        type: boolean
        default: true
      node-version:
        description: Node version to use
        type: choice
        options:
          - 18.x
          - 20.x
          - 21.x
          - 22.x
        default: 20.x

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 11-caching/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug - Check current directory and files
        run: |
          echo "Current directory:"
          pwd
          echo "List files:"
          ls -la

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: Download Cached Dependencies
        if: ${{ inputs.use-cache }}
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: 11-caching/react-app/node_modules
          key: ${{ runner.os }}-node-${{ inputs.node-version }}-deps-${{ hashFiles('11-caching/react-app/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm ci
      - name: Debug - List the dependencies of npm
        run: |
          echo "npm dependency tree"
          npm ls
      - name: Testing 
        run: npm test
      - name: Buiding
        run: npm run build
      - name: Deploying to nonprod
        run: echo "Deploying to nonprod environment"


 
